/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaceG.GestaoUsuario; // <-- Alterado

import InterfaceG.GestaoUsuario.EditarUsuarioPanel; // <-- Adicionado
import InterfaceG.GestaoUsuario.GestaoUsuariosPanel; // <-- Alterado
import com.mycompany.Gerenciamento.GestaoUsuarios; // <-- Alterado
import com.mycompany.barbearia.modelos.Usuario; // <-- Alterado
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author italo
 */
public class BuscarUsuarioPanel extends javax.swing.JPanel { // <-- Alterado

    /**
     * Creates new form BuscarUsuarioPanel
     */
    private GestaoUsuariosPanel root; // <-- Alterado

    public BuscarUsuarioPanel(GestaoUsuariosPanel root) { // <-- Alterado
        this.root = root;
        initComponents();
        carregarTodos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jEditarUsuario2 = new javax.swing.JButton(); // <-- Renomeado
        jbuscarUsuario1 = new javax.swing.JButton(); // <-- Renomeado
        jNomeUsuarioField = new javax.swing.JTextField(); // <-- Renomeado
        jLabel1 = new javax.swing.JLabel();
        jExcluirUsuario3 = new javax.swing.JButton(); // <-- Renomeado

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Usuário", "CPF", "Telefone", "Tipo", "ID" // <-- Colunas Alteradas
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jEditarUsuario2.setText("Editar");
        jEditarUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarUsuario2ActionPerformed(evt); // <-- Alterado
            }
        });

        jbuscarUsuario1.setText("Buscar");
        jbuscarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuscarUsuario1ActionPerformed(evt); // <-- Alterado
            }
        });

        jNomeUsuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeUsuarioFieldActionPerformed(evt); // <-- Alterado
            }
        });

        jLabel1.setText("Nome Usuário:"); // <-- Alterado

        jExcluirUsuario3.setText("Excluir");
        jExcluirUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirUsuario3ActionPerformed(evt); // <-- Alterado
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jNomeUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbuscarUsuario1))
                .addContainerGap(671, Short.MAX_VALUE)) // <-- Ajuste de layout se necessário
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExcluirUsuario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEditarUsuario2)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNomeUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbuscarUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarUsuario2)
                    .addComponent(jExcluirUsuario3))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>                        

    private void carregarTodos() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        List<Usuario> lista = GestaoUsuarios.getInstancia().getListaCopia(); // <-- Alterado

        for (Usuario u : lista) { // <-- Alterado
            model.addRow(new Object[]{
                u.getNome(),
                u.getUsuario(), // Assumindo que o login é 'getUsuario()'
                u.getCpf(),
                u.getTelefone(),
                u.getTipoUsuario(), // Assumindo que o tipo é 'getTipoUsuario()'
                u.getId()
            }); // <-- Linhas Alteradas
        }
    }    
    
    private void jNomeUsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jbuscarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String nome = jNomeUsuarioField.getText().trim();

        if (nome.isEmpty()) {
            carregarTodos();
            return;
        }

        try {
            // Assumindo que GestaoUsuarios tem 'buscarPorNome'
            List<Usuario> encontrados = GestaoUsuarios.getInstancia().buscarPorNome(nome); // <-- Alterado

            if (encontrados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhum usuário encontrado!"); // <-- Alterado
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (Usuario u : encontrados) { // <-- Alterado
                model.addRow(new Object[]{
                    u.getNome(),
                    u.getUsuario(),
                    u.getCpf(),
                    u.getTelefone(),
                    u.getTipoUsuario(),
                    u.getId()
                }); // <-- Linhas Alteradas
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar usuário!"); // <-- Alterado
        }
    }                                               

    private void jExcluirUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário na tabela!"); // <-- Alterado
            return;
        }

        String id = jTable1.getValueAt(row, 5).toString(); // <-- Coluna do ID mudou para 5

        int confirm = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir este usuário?", // <-- Alterado
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            GestaoUsuarios.getInstancia().remover(id); // <-- Alterado
            carregarTodos();
            JOptionPane.showMessageDialog(this, "Usuário excluído!"); // <-- Alterado
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir usuário!"); // <-- Alterado
        }
    }                                                

    private void jEditarUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário!"); // <-- Alterado
            return;
        }

        String id = jTable1.getValueAt(linha, 5).toString(); // <-- Coluna do ID mudou para 5
        Usuario usuario = GestaoUsuarios.getInstancia().buscarPorId(id); // <-- Alterado

        EditarUsuarioPanel painel = new EditarUsuarioPanel(root); // <-- Alterado
        painel.setUsuario(usuario); // <-- Assumindo que EditarUsuarioPanel tem esse método

        root.setSubPainel(painel);
    }                                               


    // Variables declaration - do not modify                     
    private javax.swing.JButton jEditarUsuario2;
    private javax.swing.JButton jExcluirUsuario3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNomeUsuarioField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbuscarUsuario1;
    // End of variables declaration                   
}