/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaceG.GestãoUsuario;



import com.mycompany.Gerenciamento.GestaoServicos;
import com.mycompany.Utilidades.TipoEstacao;
import com.mycompany.barbearia.modelos.Servico;
import com.mycompany.date_Barbearia.Barbearia_date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author italo
 */
public class CadastrarUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form CadastroClientePanel
     */
    public CadastrarUsuarioPanel() {
        initComponents();
        carregarEstacoes();
    }
    
    private void carregarEstacoes() {
        choice1.removeAll();

        for (TipoEstacao t : TipoEstacao.values()) {
            choice1.add(t.name());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            String nome = iNomeField1.getText().trim();
            String precoStr = iPrecoField2.getText().trim();
            String duracaoStr = iDuracaoINTField.getText().trim();
            String descricao = iDescricaoField3.getText().trim();
            String estacao = choice1.getSelectedItem();

            if (nome.isEmpty() || precoStr.isEmpty() || duracaoStr.isEmpty() || descricao.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
                return;
            }

            double preco = Double.parseDouble(precoStr);
            int duracao = Integer.parseInt(duracaoStr);

            Servico servico = new Servico(
                    nome,
                    preco,
                    descricao,
                    duracao,
                    TipoEstacao.valueOf(estacao)
            );

            GestaoServicos.getInstancia().adicionar(servico);
            Barbearia_date.getInstancia().salvar();
            
            
            JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso!");
          
            
            iNomeField1.setText("");
            iPrecoField2.setText("");
            iDuracaoINTField.setText("");
            iDescricaoField3.setText("");
            choice1.select(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage());
        }
  
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
