/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaceG.GestãoUsuario;

import InterfaceG.Serviços.ServicoPanel;
import com.mycompany.Gerenciamento.GestaoServicos;
import com.mycompany.barbearia.modelos.Servico;
import com.mycompany.barbearia.modelos.Usuario;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author italo
 */
public class EditarUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditarClientePanel
     */
    
    
    private final GestaoUsuariosPanel root;
    private Usuario usuario;
    
    public EditarUsuarioPanel(GestaoUsuariosPanel root) {
        this.root = root;  
        initComponents();
    }
    
    

    //mexer depois
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;

       iNomeField1.setText(usuario.getNome());
       jPrecoProdutoField1.setValue(usuario.getPreco());
       jtempoDuracaointField1.setValue(usuario.getTempoEmMinutos());
       iDescricaoField3.setText(servico.getDescricao());
    }   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        root.setSubPainel(new BuscarUsuarioPanel(root));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String nome = iNomeField1.getText().trim();
            String precoTexto = jPrecoProdutoField1.getText().replace(",", ".");
            double preco = Double.parseDouble(precoTexto);
            String descricao = iDescricaoField3.getText().trim();
            int tempo = Integer.parseInt(jtempoDuracaointField1.getText());


            JOptionPane.showMessageDialog(this, "Serviço atualizado!");

            root.setSubPainel(new BuscarUsuarioPanel(root));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void iNomeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNomeField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNomeField1ActionPerformed

    private void jtempoDuracaointField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtempoDuracaointField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtempoDuracaointField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
