/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaceG.Serviços;

import InterfaceG.Cliente.ClientesPanel;
import com.mycompany.Gerenciamento.GestaoServicos;
import com.mycompany.barbearia.modelos.Servico;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author italo
 */
public class BuscarServicosPanel extends javax.swing.JPanel{

    /**
     * Creates new form BuscarServicosPanel
     */
    
    private ServicoPanel rootPanel;

    private final ServicoPanel root;

    public BuscarServicosPanel(ServicoPanel root) {
        this.root = root;
        initComponents();
        carregarTodos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jEditarServico2 = new javax.swing.JButton();
        jbuscarServico1 = new javax.swing.JButton();
        jNomeServicoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jExcluirServico3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Descrição", "Tempo (min)", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jEditarServico2.setText("Editar");
        jEditarServico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarServico2ActionPerformed(evt);
            }
        });

        jbuscarServico1.setText("Buscar");
        jbuscarServico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuscarServico1ActionPerformed(evt);
            }
        });

        jNomeServicoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeServicoFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Serviço:");

        jExcluirServico3.setText("Excluir");
        jExcluirServico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirServico3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jNomeServicoField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbuscarServico1))
                .addContainerGap(680, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExcluirServico3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEditarServico2)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNomeServicoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbuscarServico1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarServico2)
                    .addComponent(jExcluirServico3))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

     private void carregarTodos() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        List<Servico> lista = GestaoServicos.getInstancia().getListaCopia();

        for (Servico s : lista) {
            model.addRow(new Object[]{
                s.getNome(),
                s.getPreco(),
                s.getDescricao(),
                s.getTempoEmMinutos(),
                s.getId()
            });
        }
    }  
    
    private void jNomeServicoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeServicoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeServicoFieldActionPerformed

    private void jbuscarServico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuscarServico1ActionPerformed
    
 String nome = jNomeServicoField.getText().trim();

        if (nome.isEmpty()) {
            carregarTodos();
            return;
        }

        try {
            List<Servico> encontrados = GestaoServicos.getInstancia().buscarPorNome(nome);

            if (encontrados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhum serviço encontrado!");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (Servico s : encontrados) {
                model.addRow(new Object[]{
                    s.getNome(),
                    s.getPreco(),
                    s.getDescricao(),
                    s.getTempoEmMinutos(),
                    s.getId()
                });
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar serviço!");
        }
    }//GEN-LAST:event_jbuscarServico1ActionPerformed

    private void jExcluirServico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirServico3ActionPerformed
   
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um serviço na tabela!");
            return;
        }

        String id = jTable1.getValueAt(row, 4).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir este serviço?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            GestaoServicos.getInstancia().remover(id);
            carregarTodos();
            JOptionPane.showMessageDialog(this, "Serviço excluído!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir serviço!");
        }
    }//GEN-LAST:event_jExcluirServico3ActionPerformed

    private void jEditarServico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarServico2ActionPerformed
    
        int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um serviço!");
            return;
        }

        String id = jTable1.getValueAt(linha, 4).toString();
        Servico servico = GestaoServicos.getInstancia().buscarPorId(id);

        EditarServicoPanel painel = new EditarServicoPanel(root);
        painel.setServico(servico);

        root.setSubPainel(painel);
    }//GEN-LAST:event_jEditarServico2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jEditarServico2;
    private javax.swing.JButton jExcluirServico3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNomeServicoField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbuscarServico1;
    // End of variables declaration//GEN-END:variables
}
