/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaceG.Serviços;

import InterfaceG.Serviços.ServicoPanel;
import com.mycompany.Gerenciamento.GestaoServicos;
import com.mycompany.barbearia.modelos.Servico;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author italo
 */
public class EditarServicoPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditarClientePanel
     */
    
    
    private final ServicoPanel root;
    private Servico servico;
    
    public EditarServicoPanel(ServicoPanel root) {
        this.root = root;  
        initComponents();
    }
    
    

    
    public void setServico(Servico servico) {
        this.servico = servico;

        iNomeField1.setText(servico.getNome());
        jPrecoProdutoField1.setValue(servico.getPreco());
        jtempoDuracaointField1.setValue(servico.getTempoEmMinutos());
        iDescricaoField3.setText(servico.getDescricao());
    }   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        iNomeField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPrecoProdutoField1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtempoDuracaointField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        iDescricaoField3 = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.BorderLayout());

        btnEditar.setText("Confirmar Edição");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnCancelar);

        iNomeField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNomeField1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome:");

        jPrecoProdutoField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel5.setText("Preço:");

        jLabel4.setText("tempo de duração:");

        jtempoDuracaointField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtempoDuracaointField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtempoDuracaointField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição:");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(iDescricaoField3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtempoDuracaointField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jPrecoProdutoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iNomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(iNomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPrecoProdutoField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtempoDuracaointField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(iDescricaoField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(formPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        root.setSubPainel(new BuscarServicosPanel(root));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String nome = iNomeField1.getText().trim();
            String precoTexto = jPrecoProdutoField1.getText().replace(",", ".");
            double preco = Double.parseDouble(precoTexto);
            String descricao = iDescricaoField3.getText().trim();
            int tempo = Integer.parseInt(jtempoDuracaointField1.getText());

            GestaoServicos.getInstancia().editar(
                    servico,
                    nome,
                    preco,
                    descricao,
                    tempo
            );

            JOptionPane.showMessageDialog(this, "Serviço atualizado!");

            root.setSubPainel(new BuscarServicosPanel(root));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void iNomeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNomeField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNomeField1ActionPerformed

    private void jtempoDuracaointField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtempoDuracaointField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtempoDuracaointField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTextField iDescricaoField3;
    private javax.swing.JTextField iNomeField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField jPrecoProdutoField1;
    private javax.swing.JFormattedTextField jtempoDuracaointField1;
    // End of variables declaration//GEN-END:variables
}
